### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by FrancisVila** [agauniyal/wireframe#31]
Hi,
I followed the instructions given and got an error "Error: not found: python2"
I've just reinstalled python 3.7.1 and I don't see any python2 executable there.
Here's my configuration:
Windows 10
Python 3.7.1
npm version 6.4.1

Here's the complete error:

gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\projects\wireframe-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\projects\wireframe-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\projects\wireframe-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\projects\wireframe-master\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\projects\wireframe-master\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\projects\wireframe-master\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\projects\wireframe-master\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\projects\\wireframe-master\\node_modules\\which\\which.js:13:12)\n    at F (C:\\projects\\wireframe-master\\node_modules\\which\\which.js:68:19)\n    at E (C:\\projects\\wireframe-master\\node_modules\\which\\which.js:80:29)\n    at C:\\projects\\wireframe-master\\node_modules\\which\\which.js:89:16\n    at C:\\projects\\wireframe-master\\node_modules\\isexe\\index.js:42:5\n    at C:\\projects\\wireframe-master\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\fvila\AppData\Local\Programs\Python\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\fvila\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\projects\\wireframe-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\projects\wireframe-master\node_modules\node-sass
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fvila\AppData\Roaming\npm-cache\_logs\2018-11-06T09_25_28_540Z-debug.log

**Comment by dyoungwd** [comment]
You can download python 2 for windows @ https://www.python.org/downloads/release/python-2715/
